
version: 2
 
sources:
  - name: raw
    database: DBT_DEMO
    schema: RAW
 
    tables:
      - name: CUSTOMERS
      - name: ORDERS

      - name: SALES_2024
      - name: SALES_2025

      - name: employee_details

      - name: employee
      - name: ORDER_DELINS_TAB

      - name: SALES_SOURCE

      - name: customer_master

      - name: orders_details





    